
SET(YARPDEV_NAME "stage")
SET(YARPDEV_WRAPPER "controlboard")
SET(YARPDEV_INCLUDE "StageControl.h")
SET(YARPDEV_TYPE "StageControl")

MESSAGE(STATUS "checking for STAGE libraries etc")
FIND_PACKAGE(Stage REQUIRED)
INCLUDE_DIRECTORIES(${STAGE_INCLUDE_DIR})
LINK_LIBRARIES(${STAGE_LIBRARY})
